### ISSUE TITLE
FSP Checklist

### ISSUE THREAD

**Issue by Carly-Schaaf** [JPArriola/Yulp#1]
# Wiki Page Home

- [x] Is the first page you see upon entering the wiki
- [x] Contains a welcome message
- [ ] Contains a link/placeholder for a link to the live page
- [x] All links in the right sidebar should contain each wiki page and link to the correct page
- [x] Correctly formatted
    - [x] each wiki page is listed in bullet points
    - [x] all links route the correct page

## Comments

---

# MVP List

- [x] Should have 7 MVPs.
    - [x] 3 of those are User Auth, Heroku, and Production README.
    - [x] The other 4 are from the [MVP List](https://github.com/appacademy/curriculum/blob/master/full-stack-project/proposal/mvp-list.md) or they have clarified them with you
- [x] Contains a description sentence of the app
  - [ ] Includes the following list for the 4 app specific MVPs:
    - [ ] Adequate styling
    - [ ] Smooth, bug-free navigation
    - [ ] Adequate and appropriate seeds to demonstrate the feature
- [x] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [ ] Estimates how long it will take the code each MVP
- [ ] Correctly formatted
    - [ ] MVPs are listed in an ordered list
    - [x] Each MVP is broken down into bullet points

## Comments
- You should do your production README on the last day (Friday the 21st), so you'll want to move it to the bottom of the list since things should be listed in the order in which they're done
- Also, in the title of the MVPs you'll want to estimate how long you think each feature will take you
---

# Database Schema

- [x] Contains correct datatypes
- [x] Contains appropriate constraints/details
    - [x] primary key
    - [x] not null
    - [x] unique
    - [x] indexed
    - [x] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made

- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] the table's name are `back_ticked`
    - [x] the table header column names are bolded
    - [x] columns names are lowercased and snaked_cased and `back_ticked`

## Comments
- This looks great, Josh!
- For your biz table, you'll probably want your address to be broken up into multiple columns (e.g. `address_1`, `address_2`, `city`, `state`, `zip` -- just like on a form you fill out on a website). This will allow you to more easily filter by city if you want to add a search functionality.
- For your `tags` table, you'll probably want your name column to be a string
---

# Sample State

- [x] State shape is flat!
- [x] State's keys are camelCased
- [x] All keys within the values in the state are accessible in the schema
- [x] Correctly formatted
    - [x] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text 
    - [x] Top level slices
        - [x] `entities`
        - [x] `session`
        - [x] `errors` (here or in `ui`)
        - [x] `ui` (if needed)
    - [x] Should NOT have nested slices, aka  `comments` inside of `posts`
      + Some info from other tables is ok, for instance:
        + the author username and imageurl for a post. basically any info that the user can't change
        + like count and a boolean on whether the user likes the post instead of a likes slice

## Comments
- Perfect!
---

# Backend Routes

- [x] Contains the following sections: HTML, API Endpoints(Backend)
- [x] Each route has a description
- [x] API Endpoint routes contains wildcard variables written in `snake_case`
- [x] Routes does not contain [superfluous routes](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
- [x] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
    + probably doesn't need a `GET likes` api endpoint because that info comes through the post show

## Comments
- You'll probably want your business index page to return all businesses with specific taggings, if you want to be able to search by category
- Looks great though
---

# Frontend Routes

- [x] Frontend routes contains wildcard variables written in `camelCase`
- [x] Correctly formatted
    - [x] Routes are displayed with `inline coding text` (backticks)

## Comments
- I'm not sure you need `/biz/:bizId/reviews` since I'm guessing your biz show page (`/biz/:bizId`) will render the reviews for that business

**Comment by Carly-Schaaf** [comment]
This looks great, Josh! I've left comments above, some are just suggestions. Once you address the unchecked boxes, go ahead and get started!

**Comment by JPArriola** [comment]
Hey Carly, I have updated my wiki per the comments mentioned above. Thank you!
